import Vue from 'vue'           // Give me access to the facilities of Vue
import App from './App.vue'     // Give me access to everything in App.vue

Vue.config.productionTip = false // optional - turn off the tool tip feature of Vue

new Vue({                        // Give me a new Vue object
  render: h => h(App),           // Insert the code generated by App.vue
}).$mount('#app')                // into the <div> with the id='app' in the index html
