<!-- The HTML fo the component -->
<template>
    <div class="main">
        <!-- data used in the HTML, but defined elsewhere is -->
        <!-- coded inside {{}} - mustache  expression -->
        <h2>Product Reviews for {{productName}}</h2>
        <p class="description">{{description}}</p>
        <div class="well-display">
      <div class="well">
        <span class="amount">
          <!-- data binding goes here -->
          {{averageRating}}
        </span>
        Average Rating
      </div>

      <div class="well">
        <span class="amount">
          <!-- data binding goes here -->
          
        </span>
        1 Star Review
      </div>

      <div class="well">
        <span class="amount">
          <!-- data binding goes here -->
        </span>
        2 Star Review
      </div>

      <div class="well">
        <span class="amount">
          <!-- data binding goes here -->
          {{numberOfThreeStarReviews}}
        </span>
        3 Star Review
      </div>

      <div class="well">
        <span class="amount">
          <!-- data binding goes here -->
        </span>
        4 Star Review
      </div>

      <div class="well">
        <span class="amount">
          <!-- data binding goes here -->
        </span>
        5 Star Review
      </div>
    </div>
    <!-- display each review in our display                                                                     -->
    <!-- use a v-for to generate one div for each element in our array                                          -->
    <!-- v-for requires a way to know which element it generated belongs to which element in the array          -->
    <!--                    v-bind:key identifies the element associated with the HTML element generated by v-for-->
    <!--                    we are using the review id as the key for the v-for-->
    <!-- v-bind to add a class to the div called favorited with value of favorited from the review in the array -->
    <!--                    v- bind:class ="{class-name:value/variable}" to add/remove classes on the div                             -->
    <!--                        class is added to the element if the value/variable is true-->
    <!--                        class is removed from the element if the value/variable is false -->
    <!-- if your put a v-for in the tag it generates that tag for the number of elements it sees -->
    <!--        if what you put in the v-for is not an array, but is a value, it genertes the number elements -->
    <!--        -->
    <div class="review" v-bind:class="{favorited:review.yitz}" v-for="review in reviews" v-bind:key="review.id">
        <h4>{{review.reviewer}}</h4>
        <div class="rating">
            <img src="../assets/star.png" v-for="n in review.rating" v-bind:key="n">
        </div>
        <h4>{{review.title}}</h4>
        <p>{{review.review}}</p>
        <p>
            Favorite?
            <input type="checkbox" v-model="review.yitz">
        </p>
    </div>
    </div>    <!-- end of main div - a Vue component can only have one div -->
</template>

<!-- The JavaScript for the component -->
<script>
 
// export allows the sharing of JavaScript data between components 
// export exposes data from this compontent to outside processes
// default is a special name what all you have is one object to share 
export default {    // A javaScript object to hsare with other components
    name: 'product-review',  // name of the component this export belogs to
                             // not the name: lowercase with a - bewteen parts
                             //Vue compnent filename is ProductReview
                             // The name is th filename in lowercase with a- between the words
    data() {        // the data() function is called by vue when dada is requested  by the component
        return{     // retun this objevt to Vuew when it asks for data fo this component
            productName : 'Cigar Partiess for Dummies',
            description : 'Host and plan the perfect cigar party for all your squirelly friends',
            reviews: [ // Data to be displayed by our components on the page 
            {
                reviewer: "Malcolm Gladwell",
                title: 'What a book!',
                review: "It certainly is a book. I mean, I can see that. Pages kept together with glue and there's writing on it, in some language.",
                rating: 3,
                favorite: false
            },
            {
                reviewer: "Craig Castelaz",
                title: 'Better than a swift kick in the butt!',
                review: "My bar is low.",
                rating: 4,
                favorite: true
            } 
            ] //end of the reviews array of data
        }// end of return  
    }, // end of data function

    //values computed everytime something on the page changes
    // this. - represents a property in this component - used in functions to be clear as to which property you want
     computed: {
            averageRating() {   // compute the average valuew of all ratings in the array
            let sum = this.reviews.reduce((currentSum, aReview) => {
                return currentSum + aReview.rating
            }, 0); // 0 =initial value for currentSum
            return sum/this.reviews.length; // Average is the sum of ratings/ number of ratings
            },
            numberOfThreeStarReviews() {
                return this.reviews.reduce((currenCount, aReview) => {
                if(aReview.rating === 3) {
                    currenCount++;
                }
                return currenCount;
                }, 0);

            }
        }

    
}
</script>
<!-- The CSS for the componenet -->
<style scoped>  /* Scocped says only apply this CSS to this component */
                /* without scoped the CSS would be applied to the entire page */
                /* which could change styling of other components or css has applied */

div.main {
  margin: 1rem 0;
}

div.main div.well-display {
    display: flex;
    justify-content: space-around;
}

div.main div.well-display div.well {
    display: inline-block;
    width: 15%;
    border: 1px black solid;
    border-radius: 6px;
    text-align: center;
    margin: 0.25rem;
}

div.main div.well-display div.well span.amount {
    color: darkslategray;
    display: block;
    font-size: 2.5rem;
}

div.main div.review {
    border: 1px black solid;
    border-radius: 6px;
    padding: 1rem;
    margin: 10px;
}

div.main div.review div.rating {
    height: 2rem;
    display: inline-block;
    vertical-align: top;
    margin: 0 0.5rem;
}

div.main div.review div.rating img {
    height: 100%;
}

div.main div.review p {
    margin: 20px;
}

div.main div.review h3 {
    display: inline-block;
}

div.main div.review h4 {
    font-size: 1rem;
}
div.main div.review.favorited {
    background-color: lightyellow;
}
</style>